paths:
  genomes_dir: "/home/champa/DATA/PHAGE_genome_analysis/Phage_alignement_visualisation/Test_data/project/data/genomes/"
  faa_dir: "/home/champa/DATA/PHAGE_genome_analysis/Phage_alignement_visualisation/Test_data/project/data/blast/"
  all_proteins: "/home/champa/DATA/PHAGE_genome_analysis/Phage_alignement_visualisation/Test_data/project/data/blast/all_proteins.faa"
  blast_file: "/home/champa/DATA/PHAGE_genome_analysis/Phage_alignement_visualisation/Test_data/project/data/allPV_vs_allPV.tsv"
  cds_table: "/home/champa/DATA/PHAGE_genome_analysis/Champoux_A/Analysis_05-2026/Analysis/clinker_alignements/merged_cds_predictions.csv"
  color_table: "/home/champa/DATA/PHAGE_genome_analysis/Champoux_A/Analysis_05-2026/Analysis/clinker_alignements/function_color_mapping.csv"
  output_svg: "/home/champa/DATA/PHAGE_genome_analysis/Phage_alignement_visualisation/Test_data/project/genome_comparison_all_PV_integratedBLASTconfig.svg"

blast:
  identity_threshold: 80
  coverage_threshold: 60
  num_threads: 8

plot:
  spacing: 0.8
  label_width: 25